#!/bin/sh

### BEGIN INIT INFO
# Provides:          smbd3
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Should-Start:      slapd cups
# Should-Stop:       slapd cups
# Short-Description: Samba 3 SMB/CIFS daemon (smbd3)
# Description: server to provide SMB/CIFS 3 services to clients
### END INIT INFO

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Akinori Furuta(afuruta@m7.dion.ne.jp)

SERVICE_NAME="$( /bin/basename "$0" )"
[ -z "${SERVICE_NAME}" ] && SERVICE_NAME="smbd3"
SAMBA_PREFIX=/usr/local/samba
SMBDPID="${SAMBA_PREFIX}/var/locks/smbd.pid"

if [ -z "${LD_LIBRARY_PATH}" ]
then
	export LD_LIBRARY_PATH="${SAMBA_PREFIX}/lib"
else
	export LD_LIBRARY_PATH="${SAMBA_PREFIX}/lib:${LD_LIBRARY_PATH}"
fi

export PATH="${SAMBA_PREFIX}/bin:${SAMBA_PREFIX}/sbin$( [ -n "${PATH}" ] && echo -n ":" )${PATH}"

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemons are there
test -x "${SAMBA_PREFIX}/sbin/smbd" || exit 0

. /lib/lsb/init-functions

case $1 in
	start)
		SERVER_ROLE=`"${SAMBA_PREFIX}/bin/testparm" --parameter-name="server role"  2>/dev/null | tail -1`
		if [ "$SERVER_ROLE" = "active directory domain controller" ]; then
		    exit 0
		fi

		# note: samba3 doesn't provide apparmor information
		# Update /etc/apparmor.d/local/usr.sbin.smbd-shares
		if [ -x /usr/share/samba/update-apparmor-samba-profile ]; then
			/usr/share/samba/update-apparmor-samba-profile || exit $?
		fi

		log_daemon_msg "Starting SMB/CIFS 3 daemon SMBPID=${SMBDPID}" "${SERVICE_NAME}"

		if ! start-stop-daemon -S --oknodo -x "${SAMBA_PREFIX}/sbin/smbd" -p "${SMBDPID}" -- -D; then
			log_daemon_msg "Can not start SMB/CIFS 3 daemon" "${SERVICE_NAME}"
			log_end_msg 1
			exit 1
		fi

		log_end_msg 0
		;;
	stop)

		log_daemon_msg "Stopping SMB/CIFS 3 daemon" "${SERVICE_NAME}"

		start-stop-daemon --stop --quiet --pidfile "${SMBDPID}"
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f "${SMBDPID}" ] && ! ps h `cat "${SMBDPID}"` > /dev/null
		then
			# Stale PID file, remove it (should be removed by
			# smbd itself IMHO).
			rm -f "${SMBDPID}"
		fi

		log_end_msg 0

		;;
	reload)
		log_daemon_msg "Reloading ${SAMBA_PREFIX}/lib/smb.conf" "${SERVICE_NAME}"

		start-stop-daemon --stop --quiet --signal HUP --pidfile "${SMBDPID}"

		log_end_msg 0
		;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		;;
        status)
		status_of_proc -p $SMBDPID "${SAMBA_PREFIX}/sbin/smbd" "${SERVICE_NAME}"
		exit $?
		;;
	*)
		echo "Usage: /etc/init.d/${SERVICE_NAME} {start|stop|reload|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
